topic_word_fix = {
    "iklim.": "iklim",
    "keadilam": "keadilan",
    "kesadara": "kesadaran",
    "kesadarann": "kesadaran",
    "kesadaran:": "kesadaran",
    "kesadaran.": "kesadaran",
    "kriris": "krisis",
    "keadlian": "keadilan",
    "lingungan": "lingkungan",
    "lingkugan": "lingkungan",
    "linglungan": "lingkungan",
    "lingkungan:": "lingkungan",
    "lingkungann": "lingkungan",
    "lingkungan.": "lingkungan",
    "pemerintahan:": "pemerintahan",
    "pemerintaahn": "pemerintahan",
    "pememrintahan": "pemerintahan",
    "lokall": "lokal",
    "k esehatan": "kesehatan",
    "stategi": "strategi",
    "startegi": "strategi",
    "mitasi": "mitigasi",
    "mitiagsi": "mitigasi",
    "mitigasi.": "mitigasi",
    "pemerintahan.": "pemerintahan",
    "krisisi": "krisis",
    "eduksi": "edukasi",
    "keseteraan": "kesetaraan",
    "dna": "dan",
    "risilo": "risiko",
}

topic_phrase_fix = {
    "keadilan dan kesetaraan": "keadilan dan kesetaraan lingkungan",
    "keadilan dan kesetaraan lingkung": "keadilan dan kesetaraan lingkungan",
    "keadilan dan kesetaraan lingkunga": "keadilan dan kesetaraan lingkungan",
    "eadilan dan kesetaraan lingkungan": "keadilan dan kesetaraan lingkungan",
    "mengatasi dampak yang tidak proporsional": "keadilan dan kesetaraan lingkungan",
    "kebijakan pemerintahan lokal": "kebijakan dan pemerintahan",
    "kebijakan dan pemerintahan": "kebijakan dan pemerintahan",
    "kebijakan dan pemerintah": "kebijakan dan pemerintahan",
    "kebijakan dan pemerintaha": "kebijakan dan pemerintahan",
    "kebijakan dan pemerintah lokal": "kebijakan dan pemerintahan",
    "topik kebijakan dan pemerintahan": "kebijakan dan pemerintahan",
    "kebijakan dan internasional": "kebijakan dan pemerintahan",
    "peran pemerintah lokal": "kebijakan dan pemerintahan",
    "kebijakan pemerintahan": "kebijakan dan pemerintahan",
    "perjanjian internasional": "kebijakan dan pemerintahan",
    "topik dampak krisis iklim": "dampak krisis iklim",
    "pola cuaca yang berubah": "dampak krisis iklim",
    "dampak krisis": "dampak krisis iklim",
    "bencana alam": "dampak krisis iklim",
    "energi terbarukan vs gas dalam transisi energi": "energi terbarukan",
    "perubahan iklim dan hak asasi manusia di cop26": "perubahan iklim",
    "strategi mitigas": "strategi mitigasi",
    "strategi mitigasi subtopik": "strategi mitigasi",
    "kesadaran dan edukasi": "edukasi dan literasi",
    "konservasi lingkungangkungan": "konservasi lingkungan",
    "pelestarian habitat": "konservasi lingkungan",
    "topik edukasi dan kesadaran": "edukasi dan kesadaran",
}

subtopic_word_fix = {
    "alam.": "alam",
    "cuca": "cuaca",
    "dampam": "dampak",
    "ekosisteml": "ekosistem",
    "terbarukan.": "terbarukan",
    "terbarukan:": "terbarukan",
    "kampanya": "kampanye",
    "publik.": "publik",
    "komunitas.": "komunitas",
    "proporsional.": "proporsional",
    "proposional": "proporsional",
    "habitat:": "habitat",
    "habitat.": "habitat",
    "lokal.": "lokal",
    "lokall": "lokal",
    "lokal\\": "lokal",
    "peren": "peran",
    "kota.": "kota",
    "ikliml": "iklim",
    "internasioanl": "internasional",
    "interasiona": "internasional",
    "internasional:": "internasional",
    "internasional.": "internasional",
    "internasionalan": "internasional",
    "internasionall": "internasional",
    "masyarakat dan adat": "masyarakat adat",
    "pangan.": "pangan",
    "pemetintah": "pemerintah",
    "pelestaraian": "pelestarian",
    "kemanan ": "keamanan ",
    "berubah.": "berubah",
    "udara.": "udara",
    "progam ": "program ",
    "proporsionalll": "proporsional",
    "proporsionall": "proporsional",
    "proprosional": "proporsional",
    "pertahanan": "pertanian",
    "literasi.": "literasi",
    "literasil": "literasi",
    "literasii": "literasi",
    "khusus.": "khusus",
    "komunitasi": "komunitas",
    "komumitas": "komunitas",
    "tidka": "tidak",
    "tdaik": "tidak",
    "tebrarukan": "terbarukan",
    "yangtidak": "yang tidak",
    "perancanaan": "perencanaan",
    "unknownl": "unknown",
    "unknwon": "unknown",
}
subtopic_phrase_fix = {
    "inisiatif energi terbaruk": "inisiatif energi terbarukan",
    "kampanye publi": "kampanye publik",
    "mengatasi dampak yang tidak profesional": "mengatasi dampak yang tidak proporsional",
    "dampak yang tidak proporsional": "mengatasi dampak yang tidak proporsional",
    "pemerintah lokal": "peran pemerintah lokal",
    "pemerintahan lokal": "peran pemerintah lokal",
    "peran pemerintah loka": "peran pemerintah lokal",
    "perjanjian internasiona": "perjanjian internasional",
    "perspektif masyarakat adat": "perspektif masyarakat adat tentang krisis iklim",
    "emisi gas rumah kaca (unknown)": "emisi gas rumah kaca",
    "mekanisme pertanian (unknown)": "mekanisme pertanian",
    "peran pemerintahan lokal": "peran pemetintah lokal",
    "mengatasi dampak yang tidak proporsiona": "mengatasi dampak yang tidak proporsional",
    "pertanian dan ketahanan pangan": "pertanian dan keamanan pangan",
}
